apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: test-custom-default-branch-cgya
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/tnevrlka-test/build-e2e-hocq-tenant/build-suite-test-application-epps/test-custom-default-branch-cgya@sha256:2adcd477eeb9ba4f2b3e27d754de467e03cb2d237f86ff58a14565925a2dd44b
        name: my-nginx
        resources: {}
status: {}
